# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bizgo < Formula
  desc ""
  homepage "https://github.com/Bijay2052/biz-go"
  version "1.0.3"

  on_macos do
    url "https://github.com/Bijay2052/biz-go/releases/download/v1.0.3/biz-go_1.0.3_darwin_all.tar.gz"
    sha256 "aac47ebb1cc07505a23cbecea722ddb64e90f16483195dee9c633a0312020da2"

    def install
      bin.install "biz-go"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bijay2052/biz-go/releases/download/v1.0.3/biz-go_1.0.3_linux_arm64.tar.gz"
      sha256 "5cc5dd45cfe6dfae16f9940ad2c4244fce30cd64155d85d42949a1418605f88f"

      def install
        bin.install "bizgo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Bijay2052/biz-go/releases/download/v1.0.3/biz-go_1.0.3_linux_amd64.tar.gz"
      sha256 "797efde3eda1e2a13f70c2dcee52704cd66d0900899b460a4266ce7d6878c769"

      def install
        bin.install "bizgo"
      end
    end
  end
end
